### ISSUE TITLE
Lock screen issue

### ISSUE THREAD

**Issue by Tahir03000** [paphonb/AndroidP-ify#110] opened 2018-09-06 14:42 UTC
kindly fix the lockscreen time box

**Description**
on the lock screen, there's the time on main screen, on the time like 01:23, there's now 01[]23 like box

**Steps to reproduce**
and when I change the wallpaper the msg was System UI STOPPED

**ROM info**

**Module version (build version)**

**Xposed log / logcat**
01-02 19:52:45.476 I/Xposed  (  429): -----------------
01-02 19:52:45.476 I/Xposed  (  429): Starting Xposed version 90-beta3, compiled for SDK 27
01-02 19:52:45.477 I/Xposed  (  429): Device: Nexus 6P (Huawei), Android version 8.1.0 (SDK 27)
01-02 19:52:45.477 I/Xposed  (  429): ROM: angler-userdebug 8.1.0 OPM3.171019.019 eng.sava.20180410.181913 release-keys
01-02 19:52:45.477 I/Xposed  (  429): Build fingerprint: google/angler/angler:8.1.0/OPM3.171019.019/4618994:user/release-keys
01-02 19:52:45.477 I/Xposed  (  429): Platform: arm64-v8a, 64-bit binary, system server: yes
01-02 19:52:45.477 I/Xposed  (  429): SELinux enabled: yes, enforcing: yes
01-02 19:52:45.508 I/Xposed  (  429): -----------------
01-02 19:52:45.512 I/Xposed  (  429): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-06 17:39:39.184 I/Xposed  (  429): Detected ART runtime
09-06 17:39:39.188 I/Xposed  (  429): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-06 17:39:39.697 I/Xposed  (  429): Loading modules from /data/app/xyz.paphonb.androidpify-uPe5FOIOpQnLGvtl7y5lNg==/base.apk
09-06 17:39:40.063 I/Xposed  (  429):   Loading class xyz.paphonb.androidpify.XposedHook
09-06 17:39:46.272 I/Xposed  (  430): -----------------
09-06 17:39:46.272 I/Xposed  (  430): Starting Xposed version 90-beta3, compiled for SDK 27
09-06 17:39:46.272 I/Xposed  (  430): Device: Nexus 6P (Huawei), Android version 8.1.0 (SDK 27)
09-06 17:39:46.272 I/Xposed  (  430): ROM: angler-userdebug 8.1.0 OPM3.171019.019 eng.sava.20180410.181913 release-keys
09-06 17:39:46.272 I/Xposed  (  430): Build fingerprint: google/angler/angler:8.1.0/OPM3.171019.019/4618994:user/release-keys
09-06 17:39:46.272 I/Xposed  (  430): Platform: arm64-v8a, 32-bit binary, system server: no
09-06 17:39:46.272 I/Xposed  (  430): SELinux enabled: yes, enforcing: yes
09-06 17:39:46.276 I/Xposed  (  430): -----------------
09-06 17:39:46.277 I/Xposed  (  430): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-06 17:39:48.377 I/Xposed  (  430): Detected ART runtime
09-06 17:39:48.383 I/Xposed  (  430): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-06 17:39:48.821 I/Xposed  (  430): Loading modules from /data/app/xyz.paphonb.androidpify-uPe5FOIOpQnLGvtl7y5lNg==/base.apk
09-06 17:39:49.251 I/Xposed  (  430):   Loading class xyz.paphonb.androidpify.XposedHook
09-06 17:40:06.402 I/Xposed  ( 3260): [Android P-ify] [ERROR] : onAttachedToWindow: mIconManager = null

**Comment by suphon-t** [comment] 2018-09-07 23:08
Duplicate of #75

**Closed as completed by suphon-t** 2018-09-07 23:08 UTC
